/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.info6205.menace_tictactoe.gui;

import edu.neu.info6205.menace_tictactoe.Game;
import edu.neu.info6205.menace_tictactoe.business_logic.MenaceVsMenace;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author eswar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
    }
//    public static Game game;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        mvmButton = new javax.swing.JButton();
        mvperButton = new javax.swing.JButton();
        twmButton = new javax.swing.JButton();
        twpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("TicTacToe");

        mvmButton.setText("Menace Vs Menace");
        mvmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mvmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvmButtonActionPerformed(evt);
            }
        });

        mvperButton.setText("Menace Vs Perfect");
        mvperButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mvperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvperButtonActionPerformed(evt);
            }
        });

        twmButton.setText("Train With Menace");
        twmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        twmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twmButtonActionPerformed(evt);
            }
        });

        twpButton.setText("Train With Perfect");
        twpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        twpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mvperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mvmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(twmButton)))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(heading)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mvmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvmButtonActionPerformed
        GameBoard.newObj().initialise();
        Game.player2 ="menace";
        Game game = new Game();
        game.iterationsForMenaceVsMenace=1;
        game.start();
        this.dispose();
    }//GEN-LAST:event_mvmButtonActionPerformed

    private void mvperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvperButtonActionPerformed
        
        GameBoard.newObj().initialise();
        Game.player2 ="optimal";
        Game game = new Game();
        game.iterationsForMenaceVsOptimal=1;
        game.start();
        this.dispose();
    }//GEN-LAST:event_mvperButtonActionPerformed

    private void twmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twmButtonActionPerformed
        GameBoard.newObj().initialise();
        Game.player2 ="menace";
        Game game = new Game();
        game.start();
        this.dispose();
    }//GEN-LAST:event_twmButtonActionPerformed

    private void twpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twpButtonActionPerformed
        GameBoard.newObj().initialise();
        Game.player2 ="optimal";
        Game game = new Game();
        game.start();
        this.dispose();
    }//GEN-LAST:event_twpButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heading;
    private javax.swing.JButton mvmButton;
    private javax.swing.JButton mvperButton;
    private javax.swing.JButton twmButton;
    private javax.swing.JButton twpButton;
    // End of variables declaration//GEN-END:variables
}
